# Generated by Django 5.2.17 on 2026-09-22 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaxUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_user_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('archetype', models.CharField(default='deals', max_length=32)),
                ('engine_version', models.CharField(default='1', max_length=32)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('mapping', models.JSONField(default=dict)),
                ('quality', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=100)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('headline', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('findings', models.JSONField(default=list)),
                ('coverage', models.JSONField(default=dict)),
                ('totals', models.JSONField(default=dict)),
                ('all_metrics', models.JSONField(default=dict)),
                ('ok_list', models.JSONField(default=list)),
                ('low_sample', models.JSONField(default=list)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.maxuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='engine.snapshot')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('mime', models.CharField(blank=True, max_length=127)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('miniapp', 'Miniapp'), ('demo', 'Demo')], default='miniapp', max_length=16)),
                ('columns', models.JSONField(default=list)),
                ('sample_rows', models.JSONField(default=list)),
                ('all_rows', models.JSONField(default=list)),
                ('suggested_mapping', models.JSONField(default=dict)),
                ('mapping', models.JSONField(blank=True, null=True)),
                ('status_map', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.maxuser')),
            ],
        ),
        migrations.AddField(
            model_name='snapshot',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.upload'),
        ),
    ]
