# Generated by Django 5.2.17 on 2026-09-22 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.CharField(max_length=64)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('manager', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status_raw', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('first_contact_at', models.DateTimeField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='engine.snapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', '-amount'], name='engine_deal_snapsho_734ca9_idx'), models.Index(fields=['snapshot', 'status'], name='engine_deal_snapsho_16e757_idx')],
            },
        ),
    ]
