# Generated by Django 5.2.17 on 2026-09-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
