# Generated by Django 5.2.17 on 2026-09-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_chatmessage_tool_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='guest_session',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='is_guest',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='scan_no',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='guest_session',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
