# Generated by Django 5.2.17 on 2026-09-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_snapshot_guest_session_snapshot_is_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
