# Generated by Django 5.2.17 on 2026-09-26 18:51

import engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_deal_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='discount_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, encoder=engine.models.UTF8JSONEncoder),
        ),
    ]
