# Generated by Django 5.2.17 on 2026-09-26 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_alter_deal_discount_pct_alter_deal_raw_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maxuser',
            options={'verbose_name': 'Пользователь MAX', 'verbose_name_plural': 'Пользователи MAX'},
        ),
        migrations.AddField(
            model_name='maxuser',
            name='completion_tokens',
            field=models.BigIntegerField(default=0, verbose_name='Выходные токены (completion)'),
        ),
        migrations.AddField(
            model_name='maxuser',
            name='prompt_tokens',
            field=models.BigIntegerField(default=0, verbose_name='Входные токены (prompt)'),
        ),
        migrations.AddField(
            model_name='maxuser',
            name='total_tokens',
            field=models.BigIntegerField(default=0, verbose_name='Всего токенов'),
        ),
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(db_index=True, default='chat', max_length=64)),
                ('model', models.CharField(default='openai-compatible-model', max_length=64)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usages', to='engine.snapshot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usages', to='engine.maxuser')),
            ],
            options={
                'verbose_name': 'Лог токенов LLM',
                'verbose_name_plural': 'Логи токенов LLM',
                'ordering': ['-created_at'],
            },
        ),
    ]
