# Generated by Django 5.2.17 on 2026-09-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_bitrix_moysklad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmusagelog',
            name='model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
